Repository helderjordao-dtx/workshop, pull requests merged in 2020-11, with the labels that each got.

#2 Feature/workshop 592698898
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  README.md
Labels: reviewed ok

#3 feature/workshop-593363300
  RELEASE-NOTES.md
Labels: reviewing, to review

#5 Feature/workshop 593817505
  README.md
  RELEASE-NOTES.md
Labels: to review

#7 Feature/workshop 592699324
  .github/DOCS/wrike_task_ID.png
  CONTRIBUTING.md
Labels: to review

#6 Feature/workshop 592699427
  .gitignore
  package-lock.json
  package.json
  pages/_app.js
  pages/api/hello.js
  pages/index.js
  public/favicon.ico
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
Labels: reviewed ok

#13 feature/workshop-596384511-feature-c
  .github/DOCS/ucatolica.jpg
  .github/DOCS/uevora.jpg
  .github/DOCS/uminho.jpg
  README.md
Labels: reviewed nok, reviewed ok, reviewing
